### ISSUE TITLE
Compiler errors with the library

### ISSUE THREAD

**Issue by sukeshak** [chegewara/ssd1331_driver-esp-idf#1]
Hi there,
I using the below hardware
https://www.tindie.com/products/microwavemont/esp32-dev-board-w-full-color-oled/#

and trying to compile but compiler errors

`d:/github/esp/esp-idf/make/project.mk:123: SRCDIRS variable is deprecated. These paths can be added to EXTRA_COMPONENT_DIRS or COMPONENT_DIRS instead.
CXX build/Adafruit-SSD1331-OLED-Driver-Library-esp-idf/Adafruit_SSD1331.o
D:/msys32/home/sukesh/esp/ssd1331_driver-esp-idf/components/Adafruit-SSD1331-OLED-Driver-Library-esp-idf/Adafruit_SSD1331.cpp: In member function 'void Adafruit_SSD1331::spiwrite(uint8_t)':
D:/msys32/home/sukesh/esp/ssd1331_driver-esp-idf/components/Adafruit-SSD1331-OLED-Driver-Library-esp-idf/Adafruit_SSD1331.cpp:64:14: error: 'spi_transaction_t {aka struct spi_transaction_t}' has no member named 'address'
   trans_desc.address   = 0;
              ^

D:/msys32/home/sukesh/esp/ssd1331_driver-esp-idf/components/Adafruit-SSD1331-OLED-Driver-Library-esp-idf/Adafruit_SSD1331.cpp:65:14: error: 'spi_transaction_t {aka struct spi_transaction_t}' has no member named 'command'
   trans_desc.command   = 0;
              ^

make[1]: *** [/d/github/esp/esp-idf/make/component_wrapper.mk:239: Adafruit_SSD1331.o] Error 1
make: *** [d:/github/esp/esp-idf/make/project.mk:421: component-Adafruit-SSD1331-OLED-Driver-Library-esp-idf-build] Error 2
`

Can you please help to get this resolved. Thanks in advance.

**Comment by sukeshak** [comment]
Got the compiler error fixed.
changed 
'trans_desc.address to trans_desc.addr'

'trans_desc.command to trans_desc.cmd'

**Comment by chegewara** [comment]
Yes. Its caused last esp-idf changes in spi_transaction_t struct.
